### ISSUE TITLE
Store the latest milestone payload in the snapshot

### ISSUE THREAD

**Issue by alexsporn** [gohornet/hornet#1417]
- Instead of setting the milestone as SEP, set the milestone parents as SEP
- Serialize the milestone payload into the snapshot so that it can be checked during whiteflag (TIP-29)

**Comment by muXxer** [comment]
We do not need to store the latest milestone payload in the snapshot.

We came up with another property called GenesisMilestoneIndex, which is set during bootstrapping of a network in the snapshot file.

The milestone following this GenesisMilestoneIndex ignores the previousMilestoneID check in the whiteflag, because there exists no previous milestone.
