### ISSUE TITLE
Private tangle script doesn't work outside of repo

### ISSUE THREAD

**Issue by Dr-Electron** [gohornet/hornet#1656]
**Describe the bug**

The compressed private tangle release doesn't work because it looks for a Dockerfile that doesn't exist in the archive.
So not sure if you just want to enable running a private tangle by cloning the repo, but then the release doesn't make sense imo

**To Reproduce**
- wget https://github.com/iotaledger/hornet/releases/download/v2.0.0-beta.4/HORNET-2.0.0-beta.4-private_tangle.tar.gz
- tar -xvf HORNET-2.0.0-beta.4-private_tangle.tar.gz
- ./bootstrap

**Comment by antonionardella** [comment]
Error messages:

Network bootstrap error
![image](https://user-images.githubusercontent.com/7383572/183258097-d7f7c6d4-313c-4b7e-9eb3-dfd832c3baf2.png)


docker-compose.yml is looking for a `Dockerfile` in `../` in the `bootstrap-networks`service https://github.com/iotaledger/hornet/blob/c56bca67c18201819a0e4ac72ef342bf069082a2/private_tangle/docker-compose.yml#L25

Dockerfile is not present in `../` because the upper directory does not contain it
Additionally there is no `Dockerfile` in the archive

![image](https://user-images.githubusercontent.com/7383572/183258196-d974f92e-b071-4476-8c33-2fd71afbdad4.png)
