### ISSUE TITLE
Start INX as early as possible

### ISSUE THREAD

**Issue by Dr-Electron** [gohornet/hornet#1939]
**Is your feature request related to a problem? Please describe.**

Probably an edge case, but it would actually be nice if the dashboard could start as early as possible to for example show a loading bar (while importing a snapshot for example). That way you don't need to check the logs and can be sure that hornet is doing something.

But not shure how other INX plugins should be handled then? Should inx requests just return some sort of message if the node is not online/healthy yet?
Wdyt?

**Comment by alexsporn** [comment]
Sorry, this is totally out of scope. HORNET will be replaced with iota-core and the dashboard showing a loading bar while startup is a feature creep. INX cannot be started earlier because this makes everything more complex on all extensions. We do start the inx-dashboard earlier so that you can see it running but it actually should also wait until the node is up before trying to even connect over INX.
